# Generated by Django 3.0.6 on 2020-06-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='example',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
