# Generated by Django 3.0.6 on 2020-06-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataModel', '0003_intent_is_verify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intent',
            old_name='is_verify',
            new_name='is_valid',
        ),
    ]
