# Generated by Django 3.0.6 on 2020-06-18 15:43

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('DataModel', '0004_auto_20200618_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
